# Generated by Django 3.0.3 on 2020-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('file_path', models.CharField(default=None, max_length=200)),
                ('difficulty', models.CharField(default=None, max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('times_played', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('songs_played', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
