# Generated by Django 3.0.3 on 2020-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songQuiz', '0002_auto_20200508_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(default=None, max_length=1000)),
                ('song_list', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
