# Generated by Django 3.0.3 on 2020-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songQuiz', '0004_auto_20200508_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='song_list',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
