# Generated by Django 3.0.3 on 2020-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songQuiz', '0006_auto_20200526_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='percent_correct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
